name: gh-pages

on:
  push:
    branches:
      - gh-pages
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        nodejs: [16]

    steps:
      - name: Checkout ğŸ›
      - uses: actions/checkout@v3

      - name: Setup node env ğŸ— | Use Node.js ${{ matrix.nodejs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}
          cache: "npm"
          check-latest: true

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm run install --legacy-peer-deps

      - run: npm run build
      - run: npm run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
